version: '3'
services:
# application:
#  image: avetall87/sfg-petclinic
#  ports:
#   - "8080:8080"

 db:
  image: postgres:latest
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
  restart: always
  ports:
    - "5433:5432"
  volumes:
    - /Users/avetall/Development/Storage/db_volumns/pgdata

 metrics:
  image: yandex/clickhouse-server
  restart: always
  ports:
    - "8123:8123"
    - "9000:9000"
  volumes:
    - /Users/avetall/Development/Storage/metrics_volumns/clickhouse
